cloudwatch_agent_install_method: auto
cloudwatch_agent_rpm_url: https://s3.amazonaws.com/amazoncloudwatch-agent/redhat/amd64/latest/amazon-cloudwatch-agent.rpm
cloudwatch_agent_rpm_url: < org artifactory url >/artifactory/installers/AmazonCloudWatch/1.300064.0/redhat/amd64/amazon-cloudwatch-agent.rpm


cloudwatch_agent_config_path: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
cloudwatch_agent_collectd_service_address: udp://127.0.0.1:25826
collectd_server_host: 127.0.0.1
collectd_server_port: 25826

cloudwatch_agent_metrics_namespace: JBossNew

domain: ""

collectd_base_dir: /var/lib/collectd
collectd_pid_file: /var/run/collectd.pid
collectd_plugin_dir: /usr/lib64/collectd
collectd_types_db: /usr/share/collectd/types.db
collectd_include_dir: /etc/collectd.d/
collectd_interval: 10
collectd_timeout: 2
collectd_read_threads: 5
collectd_write_threads: 5
collectd_log_level: info

cloudwatch_agent_log_collect_list:
  - file_path: /weblogs/*jbc*/DC/log/host-controller.log
    log_group_name: /jboss/host-controller
    log_stream_name: "{instance_id}-{{ ansible_hostname }}"
  - file_path: /weblogs/*jbc*/DC/log/process-controller.log
    log_group_name: /jboss/process-controller
    log_stream_name: "{instance_id}-{{ ansible_hostname }}"
  - file_path: /weblogs/*jbc*/n*/log/server.log*
    log_group_name: /jboss/serverlog
    log_stream_name: "{instance_id}-{{ ansible_hostname }}"
  - file_path: /weblogs/*jbc*/n*/log/access*.log*
    log_group_name: /jboss/accesslog
    log_stream_name: "{instance_id}-{{ ansible_hostname }}"
  - file_path: /weblogs/*jbc*/n*/log/*vgc*.log*
    log_group_name: /jboss/vgclog
    log_stream_name: "{instance_id}-{{ ansible_hostname }}"
  - file_path: /weblogs/*jbc*/n*/log/java.log*
    log_group_name: /jboss/javalog
    log_stream_name: "{instance_id}-{{ ansible_hostname }}"
  - file_path: /var/log/messages
    log_group_name: /linux/messages
    log_stream_name: "{instance_id}-{{ ansible_hostname }}"
  - file_path: /var/log/syslog
    log_group_name: /linux/syslog
    log_stream_name: "{instance_id}-{{ ansible_hostname }}"

cloudwatch_agent_collectd_conf_path: /etc/collectd.conf
cloudwatch_agent_collectd_conf_d_dir: /etc/collectd.d
cloudwatch_agent_collectd_jmx_conf_path: /etc/collectd.d/jmx.conf

cloudwatch_agent_jboss_jmx_enabled: false
cloudwatch_agent_jboss_service_name: jboss
