- block:
    - name: Restart collectd
      ansible.builtin.service:
        name: collectd
        state: restarted

    - name: Apply CloudWatch Agent config
      ansible.builtin.command: >-
        /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl
        -a fetch-config
        -m ec2
        -c file:{{ cloudwatch_agent_config_path }}
        -s
      changed_when: true

    - name: Restart CloudWatch Agent
      ansible.builtin.service:
        name: amazon-cloudwatch-agent
        state: restarted
  become: yes
  become_user: root
